### ISSUE TITLE
Color Wheel no longer showing up on 2023.3.0

### ISSUE THREAD

**Issue by conorlap** [ljmerza/light-entity-card#104]
Color Wheel no longer showing up on latest HA release 2023.3.0

This must be because they have reworked the more-info dialogue for lights etc.

**Comment by kylepyke** [comment]
Same issue here!

**Comment by nielsgl** [comment]
Ditto here, also on 2023.3.1. I tried to figure out what causes it because the `ha-color-picker` isn't updated in the frontend repository, but it seems that it is an issue with loading the contents of the color picker. When I first load the page, click on my light the popup card is empty. However when I then open the regular `more-info` page and view the color picker, close it and then open this `light-entity-card` popup again it does show. When looking at the source code, the contents of the `ha-color-picker` element is empty the first time, however, the second time after opening the regular `more-info` popup, this popup does contain the shadow root and everything in it so I guess that it has something to do with loading the data from the color picker element. Hope this information helps :)

**Comment by ljmerza** [comment]
unfortunately, there's too many break changes at this point to support this card. would need a good rewrite that i dont have the time for

**Comment by JagerSprinkles** [comment]
I noticed that if you open the details for a light and then use the color wheel there it will temporarily fix this card. Looks like it works after something else loads the color wheel on the page.

**Comment by Phoenix-DH** [comment]
Any news on this?

**Comment by ljmerza** [comment]
try v6.0.0

**Comment by Phoenix-DH** [comment]
Great 🥳 Thank you!

**Comment by kylepyke** [comment]
Thank you!! One issue, though– the color wheel no longer resizes to the card 😬
<img width="530" alt="1" src="https://user-images.githubusercontent.com/107963487/225108992-5eb7d456-8bb0-4b4e-a84e-89422a7b8c6c.png">

**Comment by JagerSprinkles** [comment]
6.0.0 is working better but does not show up if "Consolidate Entities" is off and a group is selected. 

Thank you for the update!

**Comment by SmarterHomeLife** [comment]
Thanks for the update @ljmerza

**Comment by ljmerza** [comment]
> Thank you!! One issue, though– the color wheel no longer resizes to the card 😬 

fixed in 6.0.1

**Comment by ljmerza** [comment]
> 6.0.0 is working better but does not show up if "Consolidate Entities" is off and a group is selected

should be fixed in v6.0.2

**Comment by conorlap** [comment]
Thank you @ljmerza 🥳🥳
I'm getting a weird issue where colour changes to a group causes the lights to get "stuck" for a while - seems like the Hue bridge gets overloaded with commands or something? Even if I turn the lights off in HA they remain on and don't seem to turn off until 15/20 seconds later. 

The built in colour wheel doesn't exhibit this issue.

**Comment by kylepyke** [comment]
> > Thank you!! One issue, though– the color wheel no longer resizes to the card 😬
> 
> fixed in 6.0.1

Hmm... Still having the same issue. Here is my code, if that's helpful:

```
type: vertical-stack
title: Lights
cards:
  - square: false
    columns: 2
    type: grid
    cards:
      - type: custom:vertical-stack-in-card
        cards:
          - shorten_cards: true
            consolidate_entities: false
            child_card: false
            hide_header: false
            header: ''
            color_wheel: true
            persist_features: true
            brightness: true
            color_temp: false
            white_value: false
            color_picker: true
            speed: false
            intensity: false
            force_features: true
            show_slider_percent: true
            full_width_sliders: true
            brightness_icon: weather-sunny
            white_icon: file-word-box
            temperature_icon: thermometer
            speed_icon: speedometer
            intensity_icon: transit-connection-horizontal
            smooth_color_wheel: false
            type: custom:light-entity-card
            entity: light.hearth_lamp
            effects_list: false
```
