### ISSUE TITLE
Having issues getting to work with Auto-Entities

### ISSUE THREAD

**Issue by Ltek** [ljmerza/light-entity-card#131]
I love this card and want to make it work with Auto-Entities since I have many RGB lights to control. 

It 'works' but the issue is that the excludes do not work at all. The auto-entities author blames it on this card, which I'm skeptical of so asking if anyone has this working?

here's my YAML...

```
type: custom:auto-entities
show_empty: false
card:
  type: grid
  columns: 5
  square: false
  grid_options:
    columns: auto
card_param: cards
filter:
  include:
    - domain: light
      name: "*RGB*"
      options:
        type: custom:light-entity-card
        shorten_cards: false
        consolidate_entities: false
        child_card: false
        hide_header: false
        header: ""
        color_wheel: true
        persist_features: true
        brightness: true
        color_temp: true
        white_value: true
        color_picker: true
        speed: true
        intensity: true
        force_features: false
        show_slider_percent: true
        full_width_sliders: true
        brightness_icon: weather-sunny
        white_icon: file-word-box
        temperature_icon: thermometer
        speed_icon: speedometer
        intensity_icon: transit-connection-horizontal
        effects_list: true
  exclude:
    - name: "*Left*"
    - name: "*Right*"
    - name: "*1"
    - name: "*2"
    - name: "*Unavailable"
sort:
  method: friendly_name
  reverse: false
  numeric: false
grid_options:
  columns: full
```
