### ISSUE TITLE
color_wheel: false not hiding color wheel

### ISSUE THREAD

**Issue by Tuumke** [ljmerza/light-entity-card#26]
Installed the card via HACS. Added the JS to lovelace yaml.
Added this code:
```
      - type: horizontal-stack
        cards:
          - type: custom:light-entity-card
            entity: light.woonkamer
            color_wheel: false
            color_temp: false
            effects_list: false

          - type: custom:light-entity-card
            entity: light.carport
            color_wheel: false
            color_temp: false
            effects_list: false
```

Result:

![image](https://user-images.githubusercontent.com/935617/71881767-43465f80-3133-11ea-9485-0ef6d38bd0b4.png)
