### ISSUE TITLE
group:true still renders a drop-shadow

### ISSUE THREAD

**Issue by denilsonsa** [ljmerza/light-entity-card#35]
The `group: true` seems to change the header size but not much else. The light-entity-card is still rendered with extra whitespace and drop-shadow.

![Screenshot demonstrating the bug.](https://user-images.githubusercontent.com/121676/81647268-0534b180-942d-11ea-8599-374c791ff6b3.png)

```yaml
type: entities
title: Bug in light-entity-card
entities:
  - entity: light.bath_color
  - group: true
    color_wheel: true  # Unused
    persist_features: true
    color_picker: false
    show_slider_percent: true
    full_width_sliders: true
    entity: light.bath_color
    type: 'custom:light-entity-card'
```
