### ISSUE TITLE
Problem on light groups on HA 0.114.4

### ISSUE THREAD

**Issue by inode-** [ljmerza/light-entity-card#45]
Hello,

just upgraded to HA 0.114.4 but seems that something changed and broke the card to manage light groups. I have two led lights on the same room and I have defined a group in my configuration file:
```
light:
  - platform: group
    name: luci_salotto
    entities:
      - light.led1
      - light.led2
```
With older version of HA (0.110 if I'm not wrong) using the light-entity-card on the group I was seeing 1 single button and 1 single color picker, allowing me to control both light on the same time. On the latest version of HA I'm seeing 2 different button, 2 different color picker, and doesn't allow to control the light at the same time. Something got broken?

inode
